import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { db, freeScans } from "@/lib/db";
import { CopyLink } from "./CopyLink";

// Shareable by link, never discoverable by search: these reports carry
// other people's site data, so they stay out of every index.
export async function generateMetadata({ params }: { params: Promise<{ token: string }> }): Promise<Metadata> {
  const { token } = await params;
  const [scan] = await db.select().from(freeScans).where(eq(freeScans.token, token)).limit(1);
  if (!scan) return { robots: { index: false, follow: false } };
  return {
    title: `Internal linking report for ${scan.host} · Linkagent`,
    description: `${scan.oppCount} missing internal links found on ${scan.host}.`,
    robots: { index: false, follow: false },
  };
}

// Simple teaser score: how many missing links per scanned page. Fewer
// missing links means a healthier internal link graph.
export function scoreScan(oppCount: number, pagesScanned: number): { score: number; grade: string } {
  const density = oppCount / Math.max(pagesScanned, 1);
  const score = Math.round(Math.min(95, Math.max(20, 95 - density * 25)));
  const grade = score >= 90 ? "A" : score >= 75 ? "B" : score >= 60 ? "C" : score >= 40 ? "D" : "F";
  return { score, grade };
}

export default async function ScanReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const [scan] = await db.select().from(freeScans).where(eq(freeScans.token, token)).limit(1);
  if (!scan) notFound();

  const samples = JSON.parse(scan.samples) as { from: string; to: string; anchor: string }[];
  const { score, grade } = scoreScan(scan.oppCount, scan.pagesScanned);
  const locked = Math.max(scan.oppCount - samples.length, 0);
  const gradeColor = score >= 75 ? "text-good" : score >= 55 ? "text-warn" : "text-bad";

  return (
    <div className="mx-auto max-w-2xl pt-14 pb-20">
      <div className="flex items-center justify-between gap-3">
        <p className="text-xs font-medium uppercase tracking-[0.14em] text-faint">Internal linking report</p>
        <CopyLink />
      </div>
      <div className="mt-2 flex flex-wrap items-end justify-between gap-4">
        <h1 className="text-[30px] font-semibold tracking-[-0.02em]">{scan.host}</h1>
        <div className="text-right">
          <span className={`num text-[42px] font-semibold leading-none ${gradeColor}`}>{grade}</span>
          <p className="num text-xs text-faint">{score}/100</p>
        </div>
      </div>

      <div className="card mt-6 overflow-hidden">
        <div className="border-b border-line px-5 py-4">
          <p className="text-[15px]">
            <span className="num font-semibold text-accent">{scan.oppCount}</span>{" "}
            <span className="font-medium">missing internal links found</span>{" "}
            <span className="text-muted">
              in just {scan.pagesScanned} of about {scan.totalUrls.toLocaleString()} pages
            </span>
          </p>
        </div>

        {samples.map((s, i) => (
          <div key={i} className="border-b border-line/60 px-5 py-3">
            <div className="flex items-center gap-2 text-[13px]">
              <span className="mono max-w-[200px] truncate text-faint">{s.from}</span>
              <span className="text-faint">→</span>
              <span className="mono max-w-[200px] truncate text-body">{s.to}</span>
            </div>
            <p className="mt-1 truncate text-sm text-muted">
              anchor: <mark className="anchor">{s.anchor}</mark>
            </p>
          </div>
        ))}
        {locked > 0 && (
          <div className="select-none border-b border-line/60 px-5 py-3 blur-[5px]" aria-hidden>
            <div className="flex items-center gap-2 text-[13px]">
              <span className="mono text-faint">/blog/some-post-title</span>
              <span className="text-faint">→</span>
              <span className="mono text-body">/target/page</span>
            </div>
            <p className="mt-1 text-sm text-muted">anchor: hidden</p>
          </div>
        )}

        <div className="flex flex-wrap items-center justify-between gap-3 px-5 py-4">
          <p className="text-sm text-muted">
            {locked > 0 ? (
              <>
                <span className="num font-medium text-body">{locked}</span> more found, plus the rest of the site.
              </>
            ) : (
              "A full crawl covers the whole site and finds much more."
            )}
          </p>
          <Link href={`/signup?scan=${scan.token}`} className="btn btn-primary">
            Fix these free
          </Link>
        </div>
      </div>

      <p className="mt-6 text-center text-xs text-faint">
        Generated by{" "}
        <Link href="/" className="text-muted underline underline-offset-4 hover:text-body">
          Linkagent
        </Link>
        , the open source internal linking agent. Scan your own site free.
      </p>
    </div>
  );
}
